create extension if not exists citext;
create extension if not exists pgcrypto;

-- If you installed the previous v1 schema, keep its data instead of destroying it.
do $$
begin
  if to_regclass('public.canva_access') is not null
     and not exists (
       select 1 from information_schema.columns
       where table_schema = 'public'
         and table_name = 'canva_access'
         and column_name = 'account_id'
     ) then
    if to_regclass('public.canva_access_legacy_v1') is null then
      alter table public.canva_access rename to canva_access_legacy_v1;
    end if;
  end if;
end $$;

create table if not exists public.canva_accounts (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  members_url text not null,
  invite_url text not null,
  session_bucket text not null default 'canva-private',
  session_file text not null,
  protected_emails text[] not null default '{}',
  auto_remove boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


-- Checker metadata (v3). Safe to run on an existing v2 database.
alter table public.canva_accounts
  add column if not exists last_scan_at timestamptz,
  add column if not exists last_scan_total integer not null default 0,
  add column if not exists last_scan_unauthorized integer not null default 0,
  add column if not exists last_scan_removed integer not null default 0,
  add column if not exists last_scan_error text;

create table if not exists public.canva_packages (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  duration_days integer not null check (duration_days > 0),
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.canva_access_tokens (
  id uuid primary key default gen_random_uuid(),
  token_hash text not null unique,
  token_hint text not null,
  account_id uuid not null references public.canva_accounts(id) on delete restrict,
  package_id uuid not null references public.canva_packages(id) on delete restrict,
  status text not null default 'active' check (status in ('active','consumed','disabled')),
  usage_limit integer not null default 1 check (usage_limit > 0),
  used_count integer not null default 0 check (used_count >= 0),
  expires_at timestamptz,
  created_by_telegram_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists canva_access_tokens_account_idx
  on public.canva_access_tokens(account_id);
create index if not exists canva_access_tokens_package_idx
  on public.canva_access_tokens(package_id);

create table if not exists public.canva_access (
  id uuid primary key default gen_random_uuid(),
  telegram_user_id bigint not null,
  telegram_username text,
  telegram_first_name text,
  email citext not null,
  account_id uuid not null references public.canva_accounts(id) on delete restrict,
  package_id uuid not null references public.canva_packages(id) on delete restrict,
  last_token_id uuid references public.canva_access_tokens(id) on delete set null,
  status text not null default 'active' check (status in ('active','expired','removed','blocked')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  last_seen_in_canva timestamptz,
  last_checked_at timestamptz,
  removed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(account_id, email)
);

create index if not exists canva_access_telegram_idx
  on public.canva_access(telegram_user_id);
create index if not exists canva_access_account_status_idx
  on public.canva_access(account_id, status, ends_at);

create table if not exists public.telegram_states (
  telegram_user_id bigint primary key,
  stage text not null,
  pending_token_hash text,
  updated_at timestamptz not null default now()
);

create table if not exists public.canva_audit (
  id bigint generated by default as identity primary key,
  account_id uuid references public.canva_accounts(id) on delete set null,
  access_id uuid references public.canva_access(id) on delete set null,
  email citext,
  event text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

-- Previous v1 canva_audit may already exist. Add the v2 columns if needed.
alter table public.canva_audit
  add column if not exists account_id uuid references public.canva_accounts(id) on delete set null;
alter table public.canva_audit
  add column if not exists access_id uuid references public.canva_access(id) on delete set null;

-- All app tables are server-only. The Vercel API and worker use the service role.
alter table public.canva_accounts enable row level security;
alter table public.canva_packages enable row level security;
alter table public.canva_access_tokens enable row level security;
alter table public.canva_access enable row level security;
alter table public.telegram_states enable row level security;
alter table public.canva_audit enable row level security;

revoke all on public.canva_accounts from anon, authenticated;
revoke all on public.canva_packages from anon, authenticated;
revoke all on public.canva_access_tokens from anon, authenticated;
revoke all on public.canva_access from anon, authenticated;
revoke all on public.telegram_states from anon, authenticated;
revoke all on public.canva_audit from anon, authenticated;

grant all on public.canva_accounts to service_role;
grant all on public.canva_packages to service_role;
grant all on public.canva_access_tokens to service_role;
grant all on public.canva_access to service_role;
grant all on public.telegram_states to service_role;
grant all on public.canva_audit to service_role;

-- Atomic token redemption. One-time tokens are usage_limit=1; reusable tokens are also supported.
create or replace function public.redeem_canva_token(
  p_token_hash text,
  p_telegram_user_id bigint,
  p_telegram_username text,
  p_telegram_first_name text,
  p_email citext
)
returns table (
  access_id uuid,
  email citext,
  account_id uuid,
  account_name text,
  package_id uuid,
  package_name text,
  duration_days integer,
  starts_at timestamptz,
  ends_at timestamptz,
  status text,
  invite_url text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token public.canva_access_tokens%rowtype;
  v_account public.canva_accounts%rowtype;
  v_package public.canva_packages%rowtype;
  v_existing public.canva_access%rowtype;
  v_access public.canva_access%rowtype;
  v_base timestamptz;
  v_now timestamptz := now();
begin
  select * into v_token
  from public.canva_access_tokens
  where token_hash = p_token_hash
  for update;

  if not found then raise exception 'TOKEN_INVALID'; end if;
  if v_token.status = 'disabled' then raise exception 'TOKEN_DISABLED'; end if;
  if v_token.expires_at is not null and v_token.expires_at <= v_now then
    raise exception 'TOKEN_EXPIRED';
  end if;
  if v_token.used_count >= v_token.usage_limit or v_token.status = 'consumed' then
    raise exception 'TOKEN_USED';
  end if;

  select a.* into v_account from public.canva_accounts a where a.id = v_token.account_id;
  if not found or not v_account.is_active then raise exception 'ACCOUNT_DISABLED'; end if;

  select p.* into v_package from public.canva_packages p where p.id = v_token.package_id;
  if not found or not v_package.is_active then raise exception 'PACKAGE_DISABLED'; end if;

  select a.* into v_existing
  from public.canva_access a
  where a.account_id = v_account.id and a.email = p_email
  for update;

  if found
     and v_existing.telegram_user_id <> p_telegram_user_id
     and v_existing.status = 'active'
     and v_existing.ends_at > v_now then
    raise exception 'EMAIL_ALREADY_BOUND';
  end if;

  if found and v_existing.ends_at > v_now and v_existing.status = 'active' then
    v_base := v_existing.ends_at;
  else
    v_base := v_now;
  end if;

  insert into public.canva_access (
    telegram_user_id,
    telegram_username,
    telegram_first_name,
    email,
    account_id,
    package_id,
    last_token_id,
    status,
    starts_at,
    ends_at,
    removed_at,
    updated_at
  ) values (
    p_telegram_user_id,
    p_telegram_username,
    p_telegram_first_name,
    p_email,
    v_account.id,
    v_package.id,
    v_token.id,
    'active',
    case when found and v_existing.status = 'active' and v_existing.ends_at > v_now
      then v_existing.starts_at else v_now end,
    v_base + make_interval(days => v_package.duration_days),
    null,
    v_now
  )
  on conflict (account_id, email) do update set
    telegram_user_id = excluded.telegram_user_id,
    telegram_username = excluded.telegram_username,
    telegram_first_name = excluded.telegram_first_name,
    package_id = excluded.package_id,
    last_token_id = excluded.last_token_id,
    status = 'active',
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    removed_at = null,
    updated_at = v_now
  returning * into v_access;

  update public.canva_access_tokens
  set used_count = used_count + 1,
      status = case when used_count + 1 >= usage_limit then 'consumed' else status end,
      updated_at = v_now
  where id = v_token.id;

  insert into public.canva_audit(account_id, access_id, email, event, details)
  values (
    v_account.id,
    v_access.id,
    p_email,
    'token_redeemed',
    jsonb_build_object(
      'token_id', v_token.id,
      'package_id', v_package.id,
      'duration_days', v_package.duration_days,
      'telegram_user_id', p_telegram_user_id
    )
  );

  return query
  select
    v_access.id,
    v_access.email,
    v_account.id,
    v_account.name,
    v_package.id,
    v_package.name,
    v_package.duration_days,
    v_access.starts_at,
    v_access.ends_at,
    v_access.status,
    v_account.invite_url;
end;
$$;

revoke all on function public.redeem_canva_token(text,bigint,text,text,citext) from public, anon, authenticated;
grant execute on function public.redeem_canva_token(text,bigint,text,text,citext) to service_role;


create table if not exists public.canva_member_snapshots (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.canva_accounts(id) on delete cascade,
  email citext not null,
  is_present boolean not null default true,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  last_scan_at timestamptz not null default now(),
  unique(account_id, email)
);

create index if not exists canva_member_snapshots_account_present_idx
  on public.canva_member_snapshots(account_id, is_present, email);

alter table public.canva_member_snapshots enable row level security;
revoke all on public.canva_member_snapshots from anon, authenticated;
grant all on public.canva_member_snapshots to service_role;
