create extension if not exists citext;

create table if not exists public.canva_access (
  id uuid primary key default gen_random_uuid(),
  telegram_user_id bigint not null,
  telegram_username text,
  telegram_first_name text,
  email citext not null unique,
  status text not null default 'registered',
  last_seen_in_canva timestamptz,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists canva_access_telegram_user_id_idx
  on public.canva_access(telegram_user_id);

create table if not exists public.canva_audit (
  id bigint generated by default as identity primary key,
  email citext,
  event text not null,
  details jsonb,
  created_at timestamptz not null default now()
);

alter table public.canva_access enable row level security;
alter table public.canva_audit enable row level security;

revoke all on public.canva_access from anon, authenticated;
revoke all on public.canva_audit from anon, authenticated;

grant all on public.canva_access to service_role;
grant all on public.canva_audit to service_role;
